#include <PnC/DracoPnC/TestSet/BodyTest.hpp>
#include <PnC/DracoPnC/TestSet/JointTest.hpp>
#include <PnC/DracoPnC/TestSet/WalkingTest.hpp>
#include <PnC/DracoPnC/TestSet/BalancingTest.hpp>
#include <PnC/DracoPnC/TestSet/MPCTest.hpp>
#include <PnC/DracoPnC/TestSet/MPCStandTest.hpp>
#include <PnC/DracoPnC/TestSet/MPCWalkTest.hpp>
#include <PnC/DracoPnC/TestSet/DCMWalkTest.hpp>
#include <PnC/DracoPnC/TestSet/DCMPhaseWalkingTest.hpp>
