#include <PnC/DracoPnC/TaskSet/AngularMomentumTask.hpp>
#include <PnC/DracoPnC/TaskSet/BodyRxRyZTask.hpp>
#include <PnC/DracoPnC/TaskSet/CoMLinBodyOriTask.hpp>
#include <PnC/DracoPnC/TaskSet/FootRyRzTask.hpp>
#include <PnC/DracoPnC/TaskSet/FootRzXYZTask.hpp>
#include <PnC/DracoPnC/TaskSet/LineFootTask.hpp>
#include <PnC/DracoPnC/TaskSet/PitchFootTask.hpp>
#include <PnC/DracoPnC/TaskSet/PointFootTask.hpp>
#include <PnC/DracoPnC/TaskSet/SelectedJointTask.hpp>
#include <PnC/WBC/BasicTask.hpp>
