contact_threshold: 30. # TODO (JH) : Need to be tuned

service_call:
    neck_pitch:
        kp:
        kd:
        current_limit:
    r_hip_ie:
        kp:
        kd:
        current_limit:
    r_hip_aa:
        kp:
        kd:
        current_limit:
    r_hip_fe:
        kp:
        kd:
        current_limit:
    r_knee_fe:
        kp:
        kd:
        current_limit:
    r_ankle_fe:
        kp:
        kd:
        current_limit:
    r_ankle_ie:
        kp:
        kd:
        current_limit:
    l_hip_ie:
        kp:
        kd:
        current_limit:
    l_hip_aa:
        kp:
        kd:
        current_limit:
    l_hip_fe:
        kp:
        kd:
        current_limit:
    l_knee_fe:
        kp:
        kd:
        current_limit:
    l_ankle_fe:
        kp:
        kd:
        current_limit:
    l_ankle_ie:
        kp:
        kd:
        current_limit:
    l_shoulder_fe:
        kp:
        kd:
        current_limit:
    l_shoulder_aa:
        kp:
        kd:
        current_limit:
    l_shoulder_ie:
        kp:
        kd:
        current_limit:
    l_elbow:
        kp:
        kd:
        current_limit:
    l_wrist_roll:
        kp:
        kd:
        current_limit:
    l_wrist_pitch:
        kp:
        kd:
        current_limit:
    r_shoulder_fe:
        kp:
        kd:
        current_limit:
    r_shoulder_aa:
        kp:
        kd:
        current_limit:
    r_shoulder_ie:
        kp:
        kd:
        current_limit:
    r_elbow:
        kp:
        kd:
        current_limit:
    r_wrist_roll:
        kp:
        kd:
        current_limit:
    r_wrist_pitch:
        kp:
        kd:
        current_limit:

