servo_dt: 0.001

save_freq: 50
ip_addr: "tcp://127.0.0.1:5557"
smoothing_duration: 0.1

wbc:
    regularization:
        lambda_q_ddot: 1e-8
        lambda_rf: 1e-7

    contact:
        rf_z_max: 1000.0
        w_rf: 0.

    task:
        com:
            weight: 20
            kp: [200, 200, 200]
            kd: [10, 10, 10]
        torso_ori:
            weight: 20
            kp: [100, 100, 100]
            kd: [10, 10, 10]
        upper_body_joint:
            weight: 20.
            neck_pitch:
                kp: 40.
                kd: 2.
            l_shoulder_fe:
                kp: 100.
                kd: 8.
            l_shoulder_aa:
                kp: 100.
                kd: 8.
            l_shoulder_ie:
                kp: 100.
                kd: 8.
            l_elbow_fe:
                kp: 50.
                kd: 3.
            l_wrist_ps:
                kp: 40.
                kd: 2.
            l_wrist_pitch:
                kp: 40.
                kd: 2.
            r_shoulder_fe:
                kp: 100.
                kd: 8.
            r_shoulder_aa:
                kp: 100.
                kd: 8.
            r_shoulder_ie:
                kp: 100.
                kd: 8.
            r_elbow_fe:
                kp: 50.
                kd: 3.
            r_wrist_ps:
                kp: 40.
                kd: 2.
            r_wrist_pitch:
                kp: 40.
                kd: 2.
        foot_pos:
            weight_at_contact: 60.
            weight_at_swing: 40.
            kp: [300., 300., 300.]
            kd: [30., 30., 30.]
        foot_ori:
            weight_at_contact: 60.
            weight_at_swing: 40.
            kp: [300., 300., 300.]
            kd: [30., 30., 30.]

    joint_integrator:
        vel_cutoff_freq: 2.0 # Hz
        pos_cutoff_freq: 1.0 # Hz
        max_pos_err:     0.2 # rad

    b_trq_limit: false

balancing:
    swaying_amp: [0., 0.08, 0.]
    swaying_freq: [0., 0.3, 0.]

    interpolation_local_offset: [0., 0.1, 0.]
    interpolation_duration: 3.

walking:
    ini_joint_dur: 4.
    ini_joint_pos:
        l_shoulder_aa: 0.523
        l_elbow_fe: -1.57
        r_shoulder_aa: -0.523
        r_elbow_fe: -1.57
        l_hip_aa: 0.087
        l_hip_fe: -0.785
        l_knee_fe_jp: 0.785
        l_knee_fe_jd: 0.785
        l_ankle_fe: -0.785
        l_ankle_ie: -0.087
        r_hip_aa: -0.087
        r_hip_fe: -0.785
        r_knee_fe_jp: 0.785
        r_knee_fe_jd: 0.785
        r_ankle_fe: -0.785
        r_ankle_ie: 0.087
        neck_pitch: 0.
        r_hip_ie: 0.
        l_hip_ie: 0.
        l_shoulder_fe: 0.
        r_shoulder_fe: 0.
        l_shoulder_ie: 0.
        r_shoulder_ie: 0.
        l_wrist_ps: 0.
        r_wrist_ps: 0.
        l_wrist_pitch: 0.
        r_wrist_pitch: 0.

    ini_stand_dur: 1.
    rf_z_max_time: 0.1

    com_height: 0.73
    swing_height: 0.04

    t_additional_ini_trans: 0.
    t_contact_trans: 0.45
    t_swing: 0.55
    percentage_settle: 0.9
    alpha_ds: 0.5

    nominal_footwidth: 0.28
    nominal_forward_step: 0.1
    nominal_backward_step: -0.1
    nominal_turn_radians: 0.3
    nominal_strafe_distance: 0.02
