servo_dt: 0.00125

save_freq: 50
ip_addr: "tcp://127.0.0.1:5557"

#b_exp: false
b_exp: true # Enable b_smoothing at the bottom

state_estimator:
    n_data_com_vel: [100, 100, 100]
    #n_data_com_vel: [20, 20, 20]
    n_data_ang_vel: [5, 5, 5]
    n_data_cam: [50, 50, 50]

wbc:
    regularization:
        lambda_q_ddot: 1e-7
        lambda_rf: 1e-6

    contact:
        rf_z_max: 1000.0
        w_rf: 0.
        foot_half_width: 0.03 # 8.5 / 2 (cm)
        foot_half_length: 0.05 # 22 / 2 (cm)
        mu: 0.3

    task:
        com_control_feedback_source: 0 # 0: com feedback, 1: icp feedback
        com:
            weight: 20
            sim_kp: [200, 200, 200]
            sim_kd: [10, 10, 10]
            exp_kp: [15, 30, 15]
            exp_kd: [4.0, 3.0, 1.2]

        icp:
            weight: 20
            sim_kp: [10, 10, 200]
            sim_kd: [0, 0, 10] # x, y will be ignored
            exp_kp: [5, 5, 15]
            exp_kd: [0., 0., 1.2]

        cam:
            weight: 0.
            sim_kp: [0., 0., 0.] # will be ignored
            sim_kd: [50., 50., 50.]
            exp_kp: [0., 0., 0.] # will be ignored
            exp_kd: [15., 15., 15.]

        torso_ori:
            weight: 20
            sim_kp: [100, 100, 100]
            sim_kd: [10, 10, 10]
            exp_kp: [10, 10, 10]
            exp_kd: [0.1, 0.1, 0.1]

        upper_body_joint:
            weight: 20.
            neck_pitch:
                sim_kp: 40.
                sim_kd: 2.
                exp_kp: 5.
                exp_kd: 0.
            l_shoulder_fe:
                sim_kp: 100.
                sim_kd: 8.
                exp_kp: 10.
                exp_kd: 0.
            l_shoulder_aa:
                sim_kp: 100.
                sim_kd: 8.
                exp_kp: 10.
                exp_kd: 0.
            l_shoulder_ie:
                sim_kp: 100.
                sim_kd: 8.
                exp_kp: 10.
                exp_kd: 0.
            l_elbow_fe:
                sim_kp: 50.
                sim_kd: 3.
                exp_kp: 7.
                exp_kd: 0.
            l_wrist_ps:
                sim_kp: 40.
                sim_kd: 2.
                exp_kp: 5.
                exp_kd: 0.
            l_wrist_pitch:
                sim_kp: 40.
                sim_kd: 2.
                exp_kp: 5.
                exp_kd: 0.
            r_shoulder_fe:
                sim_kp: 100.
                sim_kd: 8.
                exp_kp: 10.
                exp_kd: 0.
            r_shoulder_aa:
                sim_kp: 100.
                sim_kd: 8.
                exp_kp: 10.
                exp_kd: 0.
            r_shoulder_ie:
                sim_kp: 100.
                sim_kd: 8.
                exp_kp: 10.
                exp_kd: 0.
            r_elbow_fe:
                sim_kp: 50.
                sim_kd: 3.
                exp_kp: 7.
                exp_kd: 0.
            r_wrist_ps:
                sim_kp: 40.
                sim_kd: 2.
                exp_kp: 5.
                exp_kd: 0.
            r_wrist_pitch:
                sim_kp: 40.
                sim_kd: 2.
                exp_kp: 5.
                exp_kd: 0.
        foot_pos:
            weight_at_contact: 60.
            weight_at_swing: 40.
            sim_kp: [300., 300., 300.]
            sim_kd: [30., 30., 30.]
            exp_kp: [100, 100, 250]
            exp_kd: [0.1, 0.1, 1.2]
        foot_ori:
            weight_at_contact: 60.
            weight_at_swing: 40.
            sim_kp: [300., 300., 300.]
            sim_kd: [30., 30., 30.]
            exp_kp: [20, 20, 20]
            exp_kd: [0.1, 0.1, 0.1]

    joint_integrator:
        vel_cutoff_freq: 2.0 # Hz
        pos_cutoff_freq: 0.5 # Hz
        max_pos_err:     0.2 # rad

    b_trq_limit: false

balancing:
    swaying_amp: [0., 0.05, 0.]
    swaying_freq: [0., 0.5, 0.]

    interpolation_local_offset: [0., 0.05, 0.]
    interpolation_duration: 3.

walking:
    ini_joint_dur: 4.
    ini_joint_pos:
        l_shoulder_aa: 0.523
        l_elbow_fe: -1.57
        r_shoulder_aa: -0.523
        r_elbow_fe: -1.57
        l_hip_aa: 0.087
        l_hip_fe: -0.785
        l_knee_fe_jp: 0.785
        l_knee_fe_jd: 0.785
        l_ankle_fe: -0.785
        l_ankle_ie: -0.087
        r_hip_aa: -0.087
        r_hip_fe: -0.785
        r_knee_fe_jp: 0.785
        r_knee_fe_jd: 0.785
        r_ankle_fe: -0.785
        r_ankle_ie: 0.087
        neck_pitch: 0.
        r_hip_ie: 0.
        l_hip_ie: 0.
        l_shoulder_fe: 0.
        r_shoulder_fe: 0.
        l_shoulder_ie: 0.
        r_shoulder_ie: 0.
        l_wrist_ps: 0.
        r_wrist_ps: 0.
        l_wrist_pitch: 0.
        r_wrist_pitch: 0.

    ini_stand_dur: 1.
    rf_z_max_time: 0.1

    #com_height: 0.73
    com_height: 0.7
    swing_height: 0.04

    t_additional_ini_trans: 0.
    t_contact_trans: 0.45
    t_swing: 0.55
    percentage_settle: 0.9
    alpha_ds: 0.5

    nominal_footwidth: 0.28
    nominal_forward_step: 0.1
    nominal_backward_step: -0.1
    nominal_turn_radians: 0.3
    nominal_strafe_distance: 0.02

static_walking:
    moving_duration: 2.
    com_height: 0.7

    swing_duration: 3.
    des_foot_x_inc_local: 0.
    des_foot_y_inc_local: 0.05
    des_foot_ori_inc_local: 0. ## degrees

controller:
    waiting_count: 10
    b_smoothing: true
    #b_smoothing: false
    smoothing_duration: 0.2
