servo_dt: 0.00125

save_freq: 50
ip_addr: "tcp://127.0.0.1:5557"

#b_exp: false
b_exp: true # Enable b_smoothing at the bottom, n_data_com_vel, b_early_termination

b_joint_pos_test: false

expected_weight: 37 # [kg]

state_estimator:
    n_data_com_vel: [200, 200, 250]
    #n_data_com_vel: [20, 20, 20]
    #n_data_com_vel: [100, 100, 250]
    n_data_ang_vel: [5, 5, 5]
    n_data_cam: [50, 50, 50]
    n_data_base_accel: [10, 10, 10]

wbc:
    regularization:
        lambda_q_ddot: 1e-7
        lambda_rf: 1e-6
        #lambda_rf: 1e-7
        #lambda_rf_new: [1e-6, 1e-6, 1e-6, 1e-6, 1e-6, 1e-6, 1e-6, 1e-6, 1e-6, 1e-6, 1e-6, 1e-6] ## right foot, left foot
        lambda_rf_new: [1e-4, 1e-4, 1e-5, 1e-6, 1e-6, 1e-6, 1e-4, 1e-4, 1e-5, 1e-6, 1e-6, 1e-6] ## right foot, left foot

    contact:
        #rf_z_max: 1000.0
        rf_z_max: 450.0
        w_rf: 0.
        #foot_half_width: 0.04 # 8.5 / 2 (cm)
        foot_half_width: 0.04 # 8.5 / 2 (cm)
        #foot_half_length: 0.05 # 22 / 2 (cm)
        foot_half_length: 0.08 # 22 / 2 (cm)
        mu: 0.3
        #mu: 0.5

    task:
        com_control_feedback_source: 1 # 0: com feedback, 1: icp feedback
        com_control_feedback_height_target: 1 # 0: com height, 1: base height
        com:
            #weight: [20, 20, 20]
            weight: [60, 60, 60]
            sim_kp: [200, 200, 100]
            sim_kd: [10, 10, 5]
            ## Good until balancing
            #exp_kp: [15, 30, 20]
            #exp_kd: [4.0, 3.0, 1.5]
            #TESTING
            exp_kp: [12, 25, 20]
            exp_kd: [3.0, 2.0, 1.5]
        icp:
            weight: [1000, 1000, 1000]
            #weight: [40, 40, 20]
            sim_kp: [10, 10, 100]
            sim_kd: [0, 0, 5] # x, y will be ignored
            sim_ki: [0, 0, 0]
            #exp_kp: [0.88, 0.88, 20]
            #exp_kd: [0.06, 0.06, 1.5]
            #exp_ki: [0.0, 0.0, 0.]
            # Gains for squatting
            #exp_kp: [0.2, 0.1, 25]
            exp_kp: [0.1, 0.4, 25]
            exp_kd: [0.04, 0.04, 1.5]
            exp_ki: [1.0, 1.0, 0.]
            time_constant: 5.
        cam:
            weight: [0., 0., 0.]
            sim_kp: [0., 0., 0.] # will be ignored
            sim_kd: [50., 50., 50.]
            exp_kp: [0., 0., 0.] # will be ignored
            exp_kd: [15., 15., 15.]

        torso_ori:
            weight: [100., 100., 10.]
            #weight: [20., 20., 2.]
            #weight: [0.0002, 0.0002, 0.02]
            sim_kp: [100, 100, 100]
            #sim_kp: [100, 100, 100]
            sim_kd: [10, 10, 10]
            exp_kp: [15, 15, 10]
            exp_kd: [0.2, 0.2, 0.1]

        upper_body_joint:
            weight: [10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10]
            #weight: [20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20]
            neck_pitch:
                sim_kp: 100.
                sim_kd: 10.
                exp_kp: 5.
                exp_kd: 0.
            l_shoulder_fe:
                sim_kp: 100.
                sim_kd: 8.
                exp_kp: 10.
                exp_kd: 0.
            l_shoulder_aa:
                sim_kp: 100.
                sim_kd: 8.
                exp_kp: 10.
                exp_kd: 0.
            l_shoulder_ie:
                sim_kp: 100.
                sim_kd: 8.
                exp_kp: 10.
                exp_kd: 0.
            l_elbow_fe:
                sim_kp: 50.
                sim_kd: 3.
                exp_kp: 7.
                exp_kd: 0.
            l_wrist_ps:
                sim_kp: 40.
                sim_kd: 2.
                exp_kp: 5.
                exp_kd: 0.
            l_wrist_pitch:
                sim_kp: 40.
                sim_kd: 2.
                exp_kp: 5.
                exp_kd: 0.
            r_shoulder_fe:
                sim_kp: 100.
                sim_kd: 8.
                exp_kp: 10.
                exp_kd: 0.
            r_shoulder_aa:
                sim_kp: 100.
                sim_kd: 8.
                exp_kp: 10.
                exp_kd: 0.
            r_shoulder_ie:
                sim_kp: 100.
                sim_kd: 8.
                exp_kp: 10.
                exp_kd: 0.
            r_elbow_fe:
                sim_kp: 50.
                sim_kd: 3.
                exp_kp: 7.
                exp_kd: 0.
            r_wrist_ps:
                sim_kp: 40.
                sim_kd: 2.
                exp_kp: 5.
                exp_kd: 0.
            r_wrist_pitch:
                sim_kp: 40.
                sim_kd: 2.
                exp_kp: 5.
                exp_kd: 0.
        foot_pos:
            weight_at_contact: [10000., 10000., 10000.]
            weight_at_swing: [500., 500., 500.]
            #weight_at_contact: [40., 40., 40.]
            #weight_at_swing: [20., 20., 20.]
            sim_kp: [300., 300., 300.]
            sim_kd: [30., 30., 30.]
            #exp_kp: [100, 100, 250]
            #exp_kp: [50, 50, 100]
            exp_kp: [25, 25, 50]
            exp_kd: [0.1, 0.1, 1.2]
            #exp_kd: [0.5, 0.5, 1.5]
        foot_ori:
            weight_at_contact: [10000., 10000., 10000.]
            weight_at_swing: [500., 500., 500.]
            #weight_at_contact: [20., 20., 20.]
            #weight_at_swing: [20., 20., 20.]
            sim_kp: [300., 300., 300.]
            sim_kd: [30., 30., 30.]
            #exp_kp: [20, 20, 20]
            #exp_kp: [10, 10, 10]
            exp_kp: [5., 5., 5.]
            #exp_kd: [0.1, 0.1, 0.1]
            #exp_kd: [0.3, 0.3, 0.3]
            exp_kd: [1.5, 1.5, 1.5]

    joint_integrator:
        vel_cutoff_freq: 2.0 # Hz
        pos_cutoff_freq: 0.5 # Hz
        max_pos_err:     0.2 # rad

    b_trq_limit: false

balancing:
    #swaying_amp: [0., 0.08, 0.]
    #swaying_freq: [0., 0.2, 0.]
    #swaying_amp: [0., 0., 0.10]  # squatting behaviour
    #swaying_freq: [0., 0., 0.15]
    swaying_amp: [0., 0., 0.05]  # squatting behaviour
    swaying_freq: [0., 0., 0.15]

    interpolation_local_offset: [0., 0.05, 0.]
    interpolation_duration: 3.

walking:
    ini_joint_dur: 4.
    ini_transition_dur: 30.
    ini_joint_pos:
        l_shoulder_aa: 0.523
        l_elbow_fe: -1.57
        r_shoulder_aa: -0.523
        r_elbow_fe: -1.57
        #l_hip_aa: 0.
        l_hip_aa: 0.047
        #l_hip_aa: 0.060
        #l_hip_aa: 0.160
        l_hip_fe: -0.785
        l_knee_fe_jp: 0.785
        l_knee_fe_jd: 0.785
        l_ankle_fe: -0.785
        #l_ankle_ie: 0.
        l_ankle_ie: -0.047
        #l_ankle_ie: -0.060
        #l_ankle_ie: -0.160
        #r_hip_aa: 0.
        r_hip_aa: -0.047
        #r_hip_aa: -0.060
        #r_hip_aa: -0.160
        r_hip_fe: -0.785
        r_knee_fe_jp: 0.785
        r_knee_fe_jd: 0.785
        r_ankle_fe: -0.785
        #r_ankle_ie: 0.
        r_ankle_ie: 0.047
        #r_ankle_ie: 0.060
        #r_ankle_ie: 0.160
        neck_pitch: 0.
        r_hip_ie: 0.
        l_hip_ie: 0.
        l_shoulder_fe: 0.
        r_shoulder_fe: 0.
        l_shoulder_ie: 0.
        r_shoulder_ie: 0.
        l_wrist_ps: 0.
        r_wrist_ps: 0.
        l_wrist_pitch: 0.
        r_wrist_pitch: 0.

    ini_stand_dur: 1.
    rf_z_max_time: 0.1


    b_early_termination: false
    foot_height_threshold: 0.01

    #com_height: 0.68
    #com_height: 0.92
    #com_height: 0.90
    com_height: 0.90
    #com_height: 0.85
    #com_height: 1.

    swing_height: 0.03

    t_additional_ini_trans: 0.
    t_contact_trans: 0.45
    t_swing: 0.45
    percentage_settle: 0.9
    alpha_ds: 0.5

    #nominal_footwidth: 0.28
    nominal_footwidth: 0.20
    nominal_forward_step: 0.1
    nominal_backward_step: -0.1
    nominal_turn_radians: 0.3
    nominal_strafe_distance: 0.02

    n_steps: 5

static_walking:
    moving_duration: 3
    #com_height: 0.68
    #com_height: 0.92
    com_height: 0.90
    #com_height: 0.85
    #com_height: 1.
    com_offset: [0., 0.]

    swing_duration: 3
    des_foot_x_inc_local: 0.
    des_foot_y_inc_local: 0.0
    des_foot_ori_inc_local: 0. ## degrees

    transition_time: 1.

static_balancing:
    lifting_duration: 1.
    des_foot_height: 0.05
    landing_duration: 1.

controller:
    waiting_count: 10
    b_smoothing: true
    #b_smoothing: false
    smoothing_duration: 0.2
