servo_dt: 0.00125

save_freq: 50
ip_addr: "tcp://127.0.0.1:5557"

wbc:
    regularization:
        lambda_q_ddot: 1e-8
        lambda_rf: 1e-7

    task:
        upper_body_joint:
            weight: 20.
            neck_pitch:
                kp: 40.
                kd: 2.
            l_shoulder_fe:
                kp: 100.
                kd: 8.
            l_shoulder_aa:
                kp: 100.
                kd: 8.
            l_shoulder_ie:
                kp: 100.
                kd: 8.
            l_elbow_fe:
                kp: 50.
                kd: 3.
            l_wrist_ps:
                kp: 40.
                kd: 2.
            l_wrist_pitch:
                kp: 40.
                kd: 2.
            r_shoulder_fe:
                kp: 100.
                kd: 8.
            r_shoulder_aa:
                kp: 100.
                kd: 8.
            r_shoulder_ie:
                kp: 100.
                kd: 8.
            r_elbow_fe:
                kp: 50.
                kd: 3.
            r_wrist_ps:
                kp: 40.
                kd: 2.
            r_wrist_pitch:
                kp: 40.
                kd: 2.

        # sim gain
        foot_pos:
            weight: 40.
            #kp: [100, 100, 100]
            #kd: [5, 5, 5]
            kp: [10, 10, 10]
            kd: [0.1, 0.1, 0.1]
        foot_ori:
            weight: 40.
            #kp: [100, 100, 100]
            #kd: [5, 5, 5]
            kp: [10., 10., 10.]
            kd: [0.1, 0.1, 0.1]

    joint_integrator:
        vel_cutoff_freq: 2.0 # Hz
        pos_cutoff_freq: 1.0 # Hz
        max_pos_err: 0.2     # rad

    b_trq_limit: false

behavior:
    ini_joint_dur: 3.
    ini_joint_pos:
        l_shoulder_aa: 0.523
        l_elbow_fe: -1.57
        r_shoulder_aa: -0.523
        r_elbow_fe: -1.57
        l_hip_aa: 0.087
        l_hip_fe: -0.785
        l_knee_fe_jp: 0.785
        l_knee_fe_jd: 0.785
        l_ankle_fe: -0.785
        l_ankle_ie: -0.087
        r_hip_aa: -0.087
        r_hip_fe: -0.785
        r_knee_fe_jp: 0.785
        r_knee_fe_jd: 0.785
        r_ankle_fe: -0.785
        r_ankle_ie: 0.087
        neck_pitch: 0.
        r_hip_ie: 0.
        l_hip_ie: 0.
        l_shoulder_fe: 0.
        r_shoulder_fe: 0.
        l_shoulder_ie: 0.
        r_shoulder_ie: 0.
        l_wrist_ps: 0.
        r_wrist_ps: 0.
        l_wrist_pitch: 0.
        r_wrist_pitch: 0.
    swaying_amp: [0.02, 0., 0.05]
    swaying_freq: [0.2, 0., 0.2]

controller:
    waiting_count: 10
    b_smoothing: true
    #waiting_count: -10
    #b_smoothing: false
    smoothing_duration: 1.0
    controller_type: 2 # 0: gravity comp, 1: admittance, 2: impedance
