#include <RobotSystem/RobotModel/Robot/Draco/DracoGen/kin_eigen/include/p_BasePosX.h>
#include <RobotSystem/RobotModel/Robot/Draco/DracoGen/kin_eigen/include/p_BasePosY.h>
#include <RobotSystem/RobotModel/Robot/Draco/DracoGen/kin_eigen/include/p_BasePosZ.h>
#include <RobotSystem/RobotModel/Robot/Draco/DracoGen/kin_eigen/include/p_BaseRotX.h>
#include <RobotSystem/RobotModel/Robot/Draco/DracoGen/kin_eigen/include/p_BaseRotY.h>
#include <RobotSystem/RobotModel/Robot/Draco/DracoGen/kin_eigen/include/p_BaseRotZ.h>
#include <RobotSystem/RobotModel/Robot/Draco/DracoGen/kin_eigen/include/p_rHipYaw.h>
#include <RobotSystem/RobotModel/Robot/Draco/DracoGen/kin_eigen/include/p_rHipRoll.h>
#include <RobotSystem/RobotModel/Robot/Draco/DracoGen/kin_eigen/include/p_rHipPitch.h>
#include <RobotSystem/RobotModel/Robot/Draco/DracoGen/kin_eigen/include/p_rKnee.h>
#include <RobotSystem/RobotModel/Robot/Draco/DracoGen/kin_eigen/include/p_rAnkle.h>
#include <RobotSystem/RobotModel/Robot/Draco/DracoGen/kin_eigen/include/p_lHipYaw.h>
#include <RobotSystem/RobotModel/Robot/Draco/DracoGen/kin_eigen/include/p_lHipRoll.h>
#include <RobotSystem/RobotModel/Robot/Draco/DracoGen/kin_eigen/include/p_lHipPitch.h>
#include <RobotSystem/RobotModel/Robot/Draco/DracoGen/kin_eigen/include/p_lKnee.h>
#include <RobotSystem/RobotModel/Robot/Draco/DracoGen/kin_eigen/include/p_lAnkle.h>
#include <RobotSystem/RobotModel/Robot/Draco/DracoGen/kin_eigen/include/pcom_Draco.h>
