name: tests
on: 
  push:
    branches:
      - master
      - 'refactor/hermite-curve'
jobs:
  setup:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - run: |
          ./scripts/install/install_cmake.sh && ./scripts/install/gh_install_dart.sh 
          ./scripts/install/install_doxygen.sh && ./scripts/install/install_protobuf.sh 
          ./scripts/install/install_zmq.sh
          sudo apt install python3-pip
          pip install "pybind11[global]"
          cd ${PATH_PACKAGE}/../
          sudo git clone https://github.com/google/googletest.git 
          cd googletest &&
          git checkout tags/release-1.11.0 
          mkdir build 
          cd build 
          cmake .. && make -j4 
          sudo make install
          cd ${PATH_PACKAGE}  
          export CMAKE_PREFIX_PATH=/opt/openrobots:$CMAKE_PREFIX_PATH
          export CMAKE_PREFIX_PATH=/usr/local/include:$CMAKE_PREFIX_PATH
          ls /usr/local/include
          mkdir build 
          cd build 
          cmake .. 
          make 
          ./bin/hermite_curves_test